# Generated by Django 4.0.5 on 2022-06-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_content', '0002_remove_main_main_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='main_img',
            field=models.ImageField(null=True, upload_to='car_img/', verbose_name='Большие картинки'),
        ),
        migrations.AddField(
            model_name='main',
            name='main_mini_img',
            field=models.ImageField(null=True, upload_to='car_img/mini/', verbose_name='Маленькие картинки'),
        ),
    ]
