# Generated by Django 4.0.5 on 2022-06-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carusel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carusel',
            name='car_status',
            field=models.CharField(default='0', max_length=100, null=True, verbose_name='Статус переключателя'),
        ),
    ]
