# Generated by Django 4.0.5 on 2022-06-19 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_title', models.CharField(max_length=200, verbose_name='Название главной категории')),
                ('cat_slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewCategoryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_order_title', models.CharField(max_length=200, verbose_name='Название категории')),
                ('cat_order_slug', models.SlugField(max_length=200, unique=True)),
                ('cat_order_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.newcategory')),
            ],
        ),
        migrations.CreateModel(
            name='OrderNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_main_img', models.ImageField(upload_to='car_img_order/%Y/%m/%d/', verbose_name='Главная картинка')),
                ('order_main_img_mini', models.ImageField(blank=True, null=True, upload_to='car_img_order/%Y/%m/%d/', verbose_name='Картинка брэнда')),
                ('order_slug', models.SlugField(max_length=250, unique=True)),
                ('order_main_title', models.CharField(max_length=250, verbose_name='Название товара')),
                ('order_dop_title1', models.CharField(blank=True, max_length=400, verbose_name='Доп-характеристика1')),
                ('order_dop_title2', models.CharField(blank=True, max_length=400, verbose_name='Доп-характеристика2')),
                ('order_dop_title3', models.CharField(blank=True, max_length=400, verbose_name='Доп-характеристика3')),
                ('order_dop_title4', models.CharField(blank=True, max_length=400, verbose_name='Доп-характеристика4')),
                ('order_dop_title5', models.CharField(blank=True, max_length=400, verbose_name='Доп-характеристика5')),
                ('order_dop_title6', models.CharField(blank=True, max_length=400, verbose_name='Доп-характеристика6')),
                ('order_maim_date_add', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('order_maim_date', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('order_is_published', models.BooleanField(default=True)),
                ('order_price', models.CharField(max_length=50, verbose_name='Цена товара')),
                ('order_text', models.TextField(verbose_name='Описание')),
                ('order_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.newcategoryorder')),
            ],
        ),
        migrations.CreateModel(
            name='NewGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='gallery/%Y/%m/%d/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='order.ordernew')),
            ],
        ),
    ]
