# Generated by Django 4.0.5 on 2022-06-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_newgallery_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newcategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='newcategoryorder',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterModelOptions(
            name='ordernew',
            options={'ordering': ['-order_maim_date_add'], 'verbose_name': 'Карточка товара', 'verbose_name_plural': 'Карточка товара'},
        ),
    ]
