# Generated by Django 4.0.5 on 2022-06-19 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_newcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordernew',
            old_name='order_slug',
            new_name='slug',
        ),
    ]
