# Generated by Django 4.0.5 on 2022-06-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_order_slug_ordernew_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newcategory',
            old_name='cat_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='newcategoryorder',
            old_name='cat_order_slug',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='ordernew',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
