# Generated by Django 4.0.5 on 2022-06-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_cat_slug_newcategory_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordernew',
            old_name='order_category',
            new_name='cat',
        ),
    ]
