# Generated by Django 4.0.5 on 2022-07-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_order_category_ordernew_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernew',
            name='order_img_2',
            field=models.ImageField(blank=True, null=True, upload_to='car_img_order/%Y/%m/%d/', verbose_name='Вторая картинка'),
        ),
        migrations.AddField(
            model_name='ordernew',
            name='order_img_3',
            field=models.ImageField(blank=True, null=True, upload_to='car_img_order/%Y/%m/%d/', verbose_name='Третья картинка'),
        ),
        migrations.AddField(
            model_name='ordernew',
            name='order_img_4',
            field=models.ImageField(blank=True, null=True, upload_to='car_img_order/%Y/%m/%d/', verbose_name='Четвёртая картинка'),
        ),
        migrations.AddField(
            model_name='ordernew',
            name='order_img_5',
            field=models.ImageField(blank=True, null=True, upload_to='car_img_order/%Y/%m/%d/', verbose_name='Пятая картинка'),
        ),
        migrations.AddField(
            model_name='ordernew',
            name='order_img_6',
            field=models.ImageField(blank=True, null=True, upload_to='car_img_order/%Y/%m/%d/', verbose_name='Шестая картинка'),
        ),
    ]
